# Given the state table of a Moore machine and then input string, produce the output string generated by the machine

input = '1111'

def moore(str):
    state = 0
    output = ''
    for i in str:
        if state == 0:
            if i == 0:
                state = 0
                output = output + '1'
            else:
                state = 1
                output = output + '0'
        elif state == 1:
            if i == 0:
                state = 0
                output = output + '1'
            else:
                state = 2
                output = output + '1'
        elif state == 2:
            if i == 0:
                state = 2
                output = output + '1'
            else:
                state = 1
                output = output + '0'
    print(output)

moore(input)